import Head from "next/head";
import styles from "../styles/Home.module.css";
import { MyEditor } from "../components/Editor";
import { NoSsr } from "../components/NoSsr";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta charSet="utf-8" />
      </Head>

      <main className={styles.main}>
        <h1>Hello</h1>
        <div style={{ height: 450, width: 450, border: "1px solid black" }}>
          <NoSsr>
            <MyEditor />
          </NoSsr>
        </div>
      </main>
    </div>
  );
}
